[package]
name = "egui_skinner_addon"
version = "0.1.0"
authors = ["Jacobsky"]
publish = false
edition = "2018"
workspace = ".."

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.3"
egui = { version = "0.13", features = ["persistence"] }
godot_egui = { path = "../godot_egui" }
